### ISSUE TITLE
24LC1025動作確認 (保存)

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#11]
購入先：http://akizukidenshi.com/catalog/g/gI-03570/

**Comment by haru-11** [comment]
”TAKEYUKI”を書き込んで，読み込むことができたのでクリアでいいですか？

**Comment by tubemerc** [comment]
"TAKEYUKI"であれば問題ありません．完了で良いです．

**Comment by haru-11** [comment]
ありがとう，”TAKEYUKI”
Closeします．ライブラリの改良は今後も続けます．
