### ISSUE TITLE
浮動小数を入出力できるようにする

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#16]
魔法で．

**Comment by sksat** [comment]
https://github.com/core-rocket/momotarou/blob/utility/string/utility/example.cc
魔法です．精度は自分で指定した方が良さそう

**Comment by sksat** [comment]
出力だけですが

**Comment by sksat** [comment]
`.temp/tools/toolchains/gcc.py`を
```
self.flags["ld"].append("--specs=nano.specs")
self.flags["ld"] += ["-u _printf_float"]
self.flags["ld"] += ["-u _scanf_float"]
```
にしたらできたとのこと(newlib-nanoが使用されているため，明示的にリンクする必要がある)．
リリースビルド時は要らなさそう．

**Comment by sksat** [comment]
@tubemerc utility/stringはどうしますか？floatの入出力というよりstd::stringのサブセット(+to_string)みたいなかんじですが

**Comment by tubemerc** [comment]
floatの問題が解決したので恐らく使わない．
使うとしたら，binファイルの容量を抑えたいとき．

なので，とりあえず放置（これは好ましくない？）して，issueを閉じたい．

**Comment by sksat** [comment]
了解しました．closeします．
