### ISSUE TITLE
映像ダウンリンクするのか？

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#24]
カメラ載せることをまだ信じられていません．

**Comment by tubemerc** [comment]
映像ダウンリンクしたい人どれぐらいいますか？（したい人はリアクションお願いします）
個人的にはお金がかかりそうなのでナシです．

**Comment by sksat** [comment]
個人的にはしたいし，技術的にはできる(というかVTX載せるだけだし)のでやりたいんですが，非本質的なタスクが多そうだし今回やる必要は無いかもなと思ってます．ただ，本当に"載せるだけ"なのでそれを主目的にしたプロジェクトを別の機会にできるかは :thinking: なので今回やれるならやりたい...という気持ちもあるかんじですね．

**Comment by haru-11** [comment]
VTXはお金があれば載せていいと思う．
カメラは載せたい．機体班と調整して前に進めてほしい

**Comment by tubemerc** [comment]
ユクロがプロジェクトに入ってくれるっぽくて，やりたいと言ってくれているので，ダウンリンクする説濃厚です．

**Comment by shoji-kota** [comment]
自分も興味があります

**Comment by Yukuro** [comment]
- やろうとしている事
  - カメラからリアルタイムで映像を転送
     - [x] 3アマの取得(必須なのは4アマ)
     - [x] 無線局免許状の取得
     - [x] VTX,VRX,カメラの購入

(ここから下は完全に趣味なのでプロジェクトには関係ないかも)
  - カメラからリアルタイムでVRする
    - [ ] 魚眼レンズの購入
      - 購入予定(https://jp.rs-online.com/mobile/p/video-modules/1633896/)
    - [ ] Equirectangularへの変換

**Comment by tubemerc** [comment]
映像ダウンリンクする．
製作は #45 へ
