### ISSUE TITLE
外部電源使用するのか？

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#25]
11月大島はやるみたいですね．

**Comment by tubemerc** [comment]
外部電源導入したい人どれぐらいいますか？（したい人はリアクションお願いします）
個人的にはアリです．

**Comment by sksat** [comment]
どんな目的で，どのように導入するかによりますね...

**Comment by tubemerc** [comment]
◆利点
①長時間の風待ちによる電源の入れ替えが無くなる．
②搭載する電源の容量を減らせる（重量と予算を抑えられる）．

①に関しては電源入れ替えのオペレーションが簡素であれば解決．

◆方法
DCジャックを使えば抜くだけで電源を切り替えられるので楽．
他にはダイオードやMOSFETでスイッチ．

**Comment by sksat** [comment]
考える必要がある点として，
- "外部電源"の電力源はどのようなものか
- 機体のどこから線を出すのか
- いつ，どのように切り替えるのか
- 切り替えの瞬間の瞬断対策

などがありそうですね

**Comment by tubemerc** [comment]
11月大島の成功・失敗事例見てから設計確定させたいが，基板発注に間に合わんかもな～～

**Comment by haru-11** [comment]
水密の外から電源ONOFFができれば，外部電源はいらないとおもぅ．
外部電源をつける場合，機体側に電源端子に海水が入っても問題ないような工夫が求められる

**Comment by tubemerc** [comment]
動作時間6時間！梨！
