### ISSUE TITLE
使用電源を決める

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#27]
脳死でLiPoか？

**Comment by haru-11** [comment]
信頼と実績のLiPoでいいんじゃない．あまり悩む必要もなさそう

**Comment by tubemerc** [comment]
動作時間3.0[h], 供給7.4[V]
- main 1321.9[mAh]
- loger 343.3[mAh]
- 燃圧 105.6[mAh]
- 対気 101.6[mAh]

動作時間??[h], 供給??[V]
- 電磁弁 ????[mAh]
- カメラ ???[mAh]
- 外部給電? ???[mAh]

**Comment by tubemerc** [comment]
動作時間3時間想定は妥当であるか？
- 外部給電するかどうかによる．（しなくてもいいのでは……になっている）
- 電源ONのタイミングによる．

**Comment by tubemerc** [comment]
LiPoを使う．
#50で選定．
