### ISSUE TITLE
BBM試験計画書作成

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#39]
- [x] PMからフォーマットを受け取る．
- [ ] ロガー
- [ ] 対気速度計測系
- [ ] 燃焼室圧力計測系
- [ ] 位置情報取得系
- [ ] 高度算出系
- [ ] N2O充填量算出系
- [ ] 姿勢角算出系
- [ ] 保存(対気・燃圧・姿勢)系
- [ ] 開放判定系
- [ ] ダウンリンク系
- [ ] 地上局

**Comment by sksat** [comment]
これmilestoneその他では

**Comment by tubemerc** [comment]
ワア！
移動しました

**Comment by tubemerc** [comment]
なんだこれ？

**Comment by tubemerc** [comment]
何これ！！！！！！！！！！！！！！！！！！！！知らない！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
