### ISSUE TITLE
CIの導入

### ISSUE THREAD

**Issue by sksat** [core-rocket/momotarou#41]
雲の上の計算機にビルドさせて気持ちよく...なりたい！！！

# ToDo
- [x] cloneしてきたらコマンド何発かでビルドできるようにする
- [x] CIと闘う

**Comment by sksat** [comment]
GitHub Actionsが割とかなり楽だったので多分それでやります

**Comment by sksat** [comment]
インストールしてきたライブラリがリポジトリに入っている(各々の環境`mbed deploy`でインストールするべき)ので，まずはそれらを消す

**Comment by sksat** [comment]
作業ディレクトリにmbed-os放り込むの，仕方がないとは思うけどやっぱり美しくないな...

**Comment by sksat** [comment]
Python2は滅んで，どうぞ

**Comment by tubemerc** [comment]
これ作業中だけど動作試験したセンサのプログラムpushしても問題無い？
(今すぐにcommit,pushするものがあるわけじゃなくて，気になっただけ)

**Comment by sksat** [comment]
別ブランチでやってるのでokです。でもdevelop弄ったのでそこの更新だけしてもらえれば

**Comment by sksat** [comment]
https://github.com/core-rocket/momotarou/commit/5bfac800c31db1d5f4ca262dcd847c532d0f4818/checks?check_suite_id=347154937
寝ぼけながらなんかやったらできた

**Comment by sksat** [comment]
ただこれ一旦無視してるだけで，ADXL375だけビルドコケてます

**Comment by sksat** [comment]
https://github.com/core-rocket/momotarou/blob/ADXL375/ADXL375/ADXL375_i2c/ADXL375_i2c.h
を見てみたらコンストラクタとかからして違うので，おそらくADXL375_i2c.libに書いてある`46fcf349bdca`ではないバージョンのものなのでは．．．？というかこれPQのやつだったんですね

**Comment by sksat** [comment]
と思ったがバージョンはこれしか無いっぽい...？謎だ...
https://os.mbed.com/teams/PQ_Hybrid_Electrical_Equipment_Team/code/ADXL375_i2c/shortlog/

**Comment by sksat** [comment]
@haru-11 ADXL375ブランチにある`ADXL375_i2c`とhttps://os.mbed.com/teams/PQ_Hybrid_Electrical_Equipment_Team/code/ADXL375_i2c/ の中身が違うように思えるんですが，どうやってライブラリを持ってきましたか？

**Comment by haru-11** [comment]
@sk2sat 
PQのライブラリインポートしたんだけど、うまく動かなかったから、結局1から作り直した痕跡…
このままの状態だと良くないですかね…

**Comment by sksat** [comment]
結局１から作り直した了解です

**Comment by sksat** [comment]
@haru-11 24LC1025のライブラリ，https://os.mbed.com/users/sashida_h/code/24LC1025 に最新のものを上げてもらっていいですか？そうすると.libを使ってダウンロードすると古いバージョンのものが降ってくるので．
それとも，このライブラリはこのリポジトリ内で開発・メンテします？

**Comment by sksat** [comment]
CIは追加したのでclose
