### ISSUE TITLE
基板設計ソフトの決定

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#42]
候補
・Quadcept
・Eagle
・KiCAD

- Quadceptの場合
勝部が使い慣れているので設計ミスが減らせる（と思う）．しかし，無償版はPCBで100ピンまでしか使えないという制限アリ．勝部・指田は有償版使用可能．
設計者に担当ヶ所（100ピン以内に収まるような）を割り振って，勝部が統合する流れになる．

※マイコン＋センサ+いくつかのコネクタ+抵抗・コンデンサ＋ビア等で100ピンぐらい．1つの機能を持った基板は作れると思う．

- Eagleの場合
無料．浜田・庄司が使用経験アリ．
これからCOREがPCBをやっていくならこのソフト使うのでは？と思ってるので今回使うのはアリ．
設計者に担当ヶ所（Quadceptを使うより大量に割り振れる）を割り振って，勝部が統合する流れになる．

- KiCADの場合
無料．よく知らん．

意見，求ム．

**Comment by shoji-kota** [comment]
Quadceptを使ってみたいです。
自分はEAGLEしか使ったことがないため、他のソフトをさわってみたいと思います。
(自分はeagle,Quadceptどちらでもいいです。)

**Comment by sksat** [comment]
Quadcept，Windowsのみっぽい？

**Comment by tubemerc** [comment]
windowsのみ……
winでやるのはめんどくさい？LinuxだとEagleかKiCADだ

**Comment by sksat** [comment]
めんどくささがありますね...とはいえ僕はやるかわからん太郎なので使いやすさとかを優先して下さい

**Comment by tubemerc** [comment]
Quadceptでいくぜ！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！！
