### ISSUE TITLE
回路図作成

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#44]
[保存先(GoogleDrive)](https://drive.google.com/drive/folders/1LICPqx5Qaskk3ip6EKNtGYzf55OTYrrQ?usp=sharing)
- [x] layer1（無線など）
- [x] layer2（センサなど）
- [x] layer3（電源+ロガー）
- [x] ノーズ （_Nose_）
- [x] 電磁弁（_Solenoid valve_）

**Comment by tubemerc** [comment]
回路図layer1,2とりあえず完了．
[qprojファイル](https://drive.google.com/open?id=15ByZCZ1KrYgUPO2SzJt0-5oNLWpl3sa1)
誰か↑のファイルをQuadcept **ver10**で読み込んで回路図見れるか確かめてほしい．

**Comment by tubemerc** [comment]
メモ
- 電源基板で電圧を下げる．
- 電源・CANはEHコネクタで繋ぐ．

**Comment by haru-11** [comment]
QC ver10でqprojファイルが開けることを確認しました．

**Comment by tubemerc** [comment]
メモ
- EHコネクタの正面（背中が無い方）から見て左がGND，右がVCCとする．
    - 過去に使ったLiPoのほとんどがこのように圧着されているため．
    - 左がGNDの方が馴染みがある人はごめんなさい．
To Do
- [x] 電磁弁関係をlayer1に追加する．
- [x] TWE-Liteのピン配置見直す．
- [x] デバッグ用TX-RX付ける．
- [x] 燃圧のマイコンをlayer2に移動する．
- [ ] 昇圧回路

**Comment by tubemerc** [comment]
- UART1をSerial sensor
- UART2をSerial pc
だと正常に動作するが，逆にすると正常に動作しないことがあるという衝撃の真実に涙が止まらない．

**Comment by tubemerc** [comment]
基本UART1をserial pcに使いますが，センサなどでUARTを使う必要がある場合は，UART2をserial pcにします．

**Comment by tubemerc** [comment]
ダブルチェック完了．
