### ISSUE TITLE
PCB作成

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#51]
[保存先(GoogleDrive)](https://drive.google.com/drive/folders/1LICPqx5Qaskk3ip6EKNtGYzf55OTYrrQ?usp=sharing)
- [x] layer1（無線など）
- [x] layer2（センサなど）
- [x] layer3（電源+ロガー）
- [x] ノーズ （_Nose_）
- [x] 電磁弁（_Solenoid valve_）

**Comment by tubemerc** [comment]
電源基板(layer3)とロガー基板(layer4)を同一にしたいという気持ち、アリ．

**Comment by tubemerc** [comment]
基板減らして良いらしいので，layer3と4をくっつけます．

**Comment by tubemerc** [comment]
@shoji-kota 
最新版Quadceptファイルあげました．layer2のPCB作成を12/25までにお願いします！

中に何も入っていない緑の円形の中に納まるようにお願いします．ネジ穴も3つ付けておいてください(Φ37の円周上)．隣にある基板(layer1)を参考にしてください．
layer2の回路図を開いて，"プロジェクト"→"PCB部品配置"→回路図全体を範囲選択すると，layer2の部品だけをPCB内で移動できるようになるので便利です．

補足
配線幅：電源は0.6mm、その他は0.3mmでお願いします．

**Comment by shoji-kota** [comment]
了解しました。今夜から作業を始めたいと思います

**Comment by tubemerc** [comment]
layer2PCB受け取ったので確認します．
ぱっと見で修正する必要がある場所（こちらでやっておきます）．
- 直角配線
    - やめましょう．（https://www.noise-counterplan.com/article/14965176.html）
- GND配線
    - ベタGNDに落とすので配線しなくていいです．
- writing_2_3のSWDIOの配線ができない
    - マイコン側のポート名が間違ってました（すいません）．
- 9軸センサは中心に配置する
    - 値を正確に取るため（機軸まわりの回転）．言い忘れてました．
- 電源EHコネクタは裏側に配置する．
    - 電源基板が下にあるので．言い忘れてました．

**Comment by tubemerc** [comment]
追記
- パスコンはマイコンの各VDDピンの近くに置くので、回路図と照らし合わせて配置する（3.3Vとコンデンサが繋がっていればよいということではない）．
    - コンデンサに限らず，抵抗もセンサの遠くに配置されていることがあった．これは近くに置くことが必須ではないが，遠くする意味もないので近くに配置する．
- 無意味な表⇔裏の移動（ビア）．
    - センサのピンは表からでも裏からでも繋げることを意識するとよい．
- 配線が幅0.6なのにビアがΦ0.3だと小さすぎるので，Φ0.6にする．

**Comment by shoji-kota** [comment]
了解しました。指摘ありがとうございます。

**Comment by tubemerc** [comment]
発注完了．
