### ISSUE TITLE
審査書を倒す

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#53]
- [x] 1次審査書
    - https://drive.google.com/open?id=1wVYi7CYOEEinF2py2ivHQyszldoyTDdm
- [x] 2次審査書
    - https://drive.google.com/open?id=16oDmfx7VLvw_PeBiIRSVXodYiS02gonH
- [ ] 個別審査書
    - .

**Comment by tubemerc** [comment]
みんなで穴埋めしていこう＾＾ｂ

**Comment by Yukuro** [comment]
Github上では↑のコメントを編集できなかったのでCOREWiki上に移設しました
https://wiki.corerocket.net/議事録/2019/どんぶらこ/電装_審査書
＆
周波数に関する穴埋めをしました

**Comment by tubemerc** [comment]
電源に関して記述しました(COREwiki内で)

**Comment by tubemerc** [comment]
無線のチャンネル書きましたが、適当です．6が好きなので，
- ES920：6ch（ARIB：29）
- TWE-Lite：16ch

**Comment by tubemerc** [comment]
とりあえず1次審査書完了です．お疲れ様です．

**Comment by tubemerc** [comment]
- 無線型番ES920 -> ES920LR

**Comment by tubemerc** [comment]
2次審査書も倒していきます．
体裁は最後に整えます．
https://drive.google.com/open?id=16oDmfx7VLvw_PeBiIRSVXodYiS02gonH

**Comment by tubemerc** [comment]
少し書いた

**Comment by tubemerc** [comment]
2次審査書倒しました．やったぁ！

**Comment by tubemerc** [comment]
合格しました．
