### ISSUE TITLE
通信距離試験

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#55]
- 日程：2020/02/08
- 場所：浅川
- 目的：無線機の通信可能距離が十分であることを確認する．
    - 距離：1[km]（これは妥当か？到達高度：2843）
- その他
    - ES920とトワは一緒にやる．
    - Tramp-HVは黒澤と都合が合えば．

**Comment by tubemerc** [comment]
暫定浅川なので，日曜に集まった時に数人or平日に首都大生でやる．

**Comment by tubemerc** [comment]
@sk2sat 
これやりたいので、2/7までにES920が日野にある状態にしたいんですが、来れますか？
今日野にあるES920が壊れてなければ来れなくても大丈夫ですが……(木曜までに確認します)

**Comment by sksat** [comment]
明日研究室での発表が終わったら春休みなので，2/7までに日野に行くのも浅川に行くのも可能太郎です

**Comment by tubemerc** [comment]
やった〜〜〜〜〜〜〜〜！！！！
2/8に来れる自信があれば当日でもいいんですが、自身がなければ一度来てください！！！！
金曜日以外は僕が日野にいます、たぶん

**Comment by tubemerc** [comment]
直線距離で約2.5[km]稼げてすごい（ただし線路を2本挟む）

![2020-02-06 15 01 22 www google co jp b385fdc77175](https://user-images.githubusercontent.com/54838270/73910065-973e9280-48f1-11ea-9e94-7fc224269ca6.png)

**Comment by tubemerc** [comment]
①浅川に行く．
②1人が自転車に無線を載せて走る．
③残った人が受信する．
③1km離れても無線が届く．
④うれしい．

という流れで行います．
使用する無線機は
- Tramp-HV
- TWE-Lite RED
- TWE-Lite BLUE
- ES920LR

です．

**Comment by tubemerc** [comment]
無線機をブレボに載せるか基板に載せるか悩み中です
基板ですぐ動かなかったらブレボでやります

**Comment by tubemerc** [comment]
ざっくり届いた距離
- ES920 2.5[km]
- トワ赤 500[m]

**Comment by sksat** [comment]
えっ...わたしのトワ，カスすぎ...！？

**Comment by sksat** [comment]
あとトワはマ〜ジで間に障害物あると厳しい．ES920LRはかなり届きはするけどこれも遠いとダメな時はダメ．掲げたら復活などがあるのでやっぱり障害物...？

**Comment by haru-11** [comment]
Let's go ENOSHIMA！

**Comment by shoji-kota** [comment]
江ノ島で通信実験やってたら、2時間ほどだったのにも関わらず3回「なにやってるの？」と聞かれた思い出があります。（ビーチで遊んでる人の中をパソコン持ちながら移動してたらそうなりますよね…笑）

**Comment by tubemerc** [comment]
ロケット->地上局の試験はしたけど，地上局からのコマンド->ロケットの試験するの完全に忘れてたぁ！

**Comment by sksat** [comment]
ACKは送り合ってただろうし，いけるやろ　みつを

**Comment by tubemerc** [comment]
2/19(水)
Tramp-HV通信距離試験

**Comment by tubemerc** [comment]
やったぁ！
