### ISSUE TITLE
開放判定試験

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#58]
- 日程：2020/02/13
- 場所：日野C
- 目的：開放判定条件が妥当であることを確認する．
- 内容
    - 気圧．
    - タイマー．

**Comment by tubemerc** [comment]
ソレノイド動かすぞ！

**Comment by tubemerc** [comment]
ソレノイド動かないぞ！

MOSFETが悪い感じがあるので，新しいのを買ってきます，明日．

**Comment by tubemerc** [comment]
ソレノイド動いたぞ！

ゲートの分圧の抵抗1つ外したら動いたので，入力電圧足りなかったんだなぁという感じです．

**Comment by tubemerc** [comment]
フライトピン抜いたらソレノイドバルブが動作するプログラム（何それは？）で基板上でも動いたぞ！

**Comment by sksat** [comment]
天才じゃ〜ん　何それ

**Comment by tubemerc** [comment]
試験にES920LRが必要，部室にあるヤツ動作試験する
動く-> プログラムさえあればよい
動かない -> sksatがES920LR持ってくる

**Comment by tubemerc** [comment]
@sk2sat 
2/13に日野来れますか！？（2/12でもよい）
部室にあったES920LRが微妙（"￤馞"としか応答してくれない）なので，無線機が欲しいです．

**Comment by sksat** [comment]
同人誌の修羅場が終わり，sksat，再来

**Comment by sksat** [comment]
2/13可です

**Comment by tubemerc** [comment]
開放判定、コマンドで開放するパターンのヤツのログ取るのわすれてたぁ

**Comment by tubemerc** [comment]
2/16にコマンドのやつやる

**Comment by tubemerc** [comment]
コマンドは無し！やったぁ！
