### ISSUE TITLE
コネクタを作る

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#60]
- コネクタを作る

| 完成 | 種別 | ピン数 | 長さ[mm] | 配色（基本左が黒） | 多芯 |
| ---------- | -------- | -------- | -------- | -------- | -------- |
| x | CAN(1-2) | 3 | 40 | 黒白赤 | - |
| x | CAN(1-nose) | 3 | 900 | 黒白赤 | x |
|  | 電源(1-power) | 2 | 200 | 黒赤 | - |
|  | 電源(2-power) | 2 | 200 | 黒赤 | - |
| x | 電磁弁 | 2 | 400 | 黒白 | x |
| x | 燃圧_1 | 3 | 500 | 黒白赤 | x |
| x | 燃圧_2 | 3 | 1500 | 黒白赤 | x |
| x | バルブ電装 | 3 | 1000? | 黒白赤 | x |

※色は黒赤以外はなんでもよい．
※CAN(1-nose)，電磁弁，燃圧，フライトピンはケーブルグランドを通す．
※多芯ｹｰﾌﾞﾙ：Φ3～6[mm]

- Li-Poバッテリの圧着

| 完了 | 種別 | ピン数 | 長さ[mm] |
| ---------- | -------- | -------- | -------- |
|  | LiPo2000mAh*2 (メイン)| 4 | 100 |
|  | LiPo2000mAh*2 (メイン)| 4 | 100 |
|  | LiPo860mAh*2 (ロガー)| 4 | 100 |
|  | LiPo400mAh*2 (ノーズ)| 4 |  |
|  | LiPo400mAh*2 (電磁弁)| 4 |  |

※長さは最低値，もっと長くてもよい．
※カメラ・バルブは除く

**Comment by tubemerc** [comment]
多芯ケーブル選定しました．
- VCTF 3X0.3SQ-7
https://jp.misumi-ec.com/vona2/detail/222000357135/?ProductCode=VCTF 3X0.3SQ-7
- VCTF 2X0.3SQ-3
https://jp.misumi-ec.com/vona2/detail/222000357135/?ProductCode=VCTF 2X0.3SQ-3

@shoji-kota と @Kazu-hub は表の多芯ｹｰﾌﾞﾙにxがついてるヤツはケーブル届いてからお願いします．
xがついてないヤツもケーブル購入したら頼みます．

**Comment by tubemerc** [comment]
ユクロとぐんまちゃんに材料買ってもらいました．

**Comment by tubemerc** [comment]
一部のコネクタの片側完了．
長さ確定次第完成．
@shoji-kota  @Kazu-hub 感謝……！

**Comment by tubemerc** [comment]
![配線図概要](https://user-images.githubusercontent.com/54838270/74336058-ec424300-4de0-11ea-946d-cddc7945d2ce.png)

**Comment by tubemerc** [comment]
中継コネクタはSMコネクタ にします．
- [SMR-03V-B【2.5mm】SMコネクタ リセプタクルハウジング 3P](https://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=EEHD-0GZX)
- [BYM-001T-P0.6【2.5mm】RCYコネクタ リセプタクルハウジング用ピンコンタクトピン](https://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=EEHD-074B)
- [SMP-03V-BC【2.5mm】SMコネクタ プラグハウジング 3P](https://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=EEHD-0H33)
- [BHF-001T-0.8BS【2.5mm】SM/NHコネクタ兼用 プラグハウジング用ソケットコンタクトピン](https://www.sengoku.co.jp/mod/sgk_cart/detail.php?code=EEHD-0GZV)

**Comment by tubemerc** [comment]
電源ケーブル -> 電装高さ内訳確定後
フライトピンケーブル -> フライトピン仕様確定してから

**Comment by tubemerc** [comment]
全てのケーブルの仕様が確定したので残り作れます
残り
- 電源(1-power)
- 電源(2-power)

**Comment by tubemerc** [comment]
![配線図_2](https://user-images.githubusercontent.com/54838270/74638074-94278a00-51ae-11ea-8703-c1d57f6a1c03.png)

**Comment by tubemerc** [comment]
コネクタ完了
残り：Li-Po，予備

**Comment by tubemerc** [comment]
バルブ電装のケーブル忘れてたぁ

@haru-11 水密から伸びるのはサーボ用の3本でよい？

**Comment by haru-11** [comment]
良いです。

**Comment by tubemerc** [comment]
残りはバルブ電装だけど。。。。。。まあええか
