### ISSUE TITLE
再発注基板が来ない

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#65]
再発注基板が来ないため，ノーズ電装とロガー電装が完成しない．

発送が止まっているらしいが，製造も止まっている感じがする．
製造も止まってるのか？急いでくれとメールで問い合わせています．

【来ない場合の対処法】
- 国内で再発注
    - お金がかかるため，微妙．
        - ユニクラフトのサービスでノーズ基板とロガー基板のどちらかなら無料で作れる．
            - 作るとしたらノーズ基板．
- ユニバーサル基板で作る
    - DIP化キット等を買う必要があるが~~現実的~~大きさ的に厳しい．
- 古い基板を使う
    - ロガー基板は気圧が取れなくなる．フラッシュメモリに再挑戦できる．
    - ノーズ基板は使えない．ユニバーサル基板でやった方がよい．

**Comment by sksat** [comment]
ワンチャン古い基板で突き進むかんじですかね？

**Comment by tubemerc** [comment]
よく考えたらユニバーサル基板にロガーもノーズも収まる未来が見えないので，
- ロガーは古い基板で突き進む（気圧をロガーで取らない）
- ノーズは[ユニクラフトのヤツ](https://unicraft-jp.com/pcb/free_pcb.shtml)で発注する

がよい気がする．
2/23迄にSeeedからよい返信（製造開始するとか発送開始する）が貰えなかったら方針決定します．

**Comment by sksat** [comment]
気圧が取れないと→→→かなしい！！！と思ったけどメイン電装でちゃんと保存できれば→→→うれしい！！！！！ということを思い出した

**Comment by haru-11** [comment]
ちなみに、落ち武者はステータスが「製造」に変わったらしいが…

**Comment by tubemerc** [comment]
直ちにfile reviewやるよ～～んというメールが来ました

**Comment by tubemerc** [comment]
PCB in Production
2020 Feb 19 18:09:16

作り始めたぁ

**Comment by tubemerc** [comment]
現在：品質確認（基板製作の最終ﾌｪｰｽﾞ）
今のところ，普段と比べると3日の遅延．

**Comment by tubemerc** [comment]
PCB Finished
2020 Feb 25 15:23:19

**Comment by tubemerc** [comment]
発送済
2/28到着予定

**Comment by tubemerc** [comment]
来た
