### ISSUE TITLE
MPXV5050DP動作確認 (対気)

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#8]
購入先：https://www.mouser.jp/ProductDetail/Measurement-Specialties/4525DO-DS5AI015DP?qs=sGAEpiMZZMvhQj7WZhFIAITlx0ciJelDE%252Bij0fSI5uGknNsgNSIQoA==

**Comment by tubemerc** [comment]
ぐんまちゃん曰く，
- このコードで動く https://forum.arduino.cc/index.php?topic=575210.0
- 測定範囲が1psiだと-0.5~0.5psiの範囲で測定可能なので単純に速度出すときは0.5psiの範囲でしか測定できない．
- ピトー管を逆に接続してもプログラムの中で絶対値取ってるのでデータは取得可能．

**Comment by tubemerc** [comment]
値が妥当かどうか保証する方法決めなければ……

**Comment by haru-11** [comment]
風洞か，風速計買う
あとSTM32で動かさんと
Amazonの[コレ](https://www.amazon.co.jp/OTraki-GM816-%E3%82%B3%E3%83%B3%E3%83%91%E3%82%AF%E3%83%88-%E3%82%A2%E3%83%8D%E3%83%A2%E3%83%A1%E3%83%BC%E3%82%BF%E3%83%BC-%E5%B9%B3%E5%9D%87%E5%80%A4%E8%A1%A8%E7%A4%BA%E5%8F%AF%E8%83%BD/dp/B06ZZB2VM4/ref=sr_1_2?__mk_ja_JP=%E3%82%AB%E3%82%BF%E3%82%AB%E3%83%8A&keywords=%E9%A2%A8%E9%80%9F%E8%A8%88&qid=1572403997&s=instant-video&sr=8-2)とか

**Comment by tubemerc** [comment]
差圧系の測定レンジ足りないのでこっち買う
https://www.mouser.jp/ProductDetail/Measurement-Specialties/4525DO-DS5AI015DP?qs=sGAEpiMZZMvhQj7WZhFIAITlx0ciJelDE%252Bij0fSI5uGknNsgNSIQoA%3D%3D

**Comment by tubemerc** [comment]
@Kazu-hub 
11/10(日)にコレをSTM32で動かしてほしいんだけどできる？

**Comment by tubemerc** [comment]
@Kazu-hub @omuro-kairi 
大室にピトー管と差圧センサ渡しました．
浜田は11月大島のタスクをこなしてください．

**Comment by tubemerc** [comment]
NAFTが使ってたヤツの50kPaまでいける版
今使おうとしてるやつの半分の値段(2000円)
https://www.mouser.jp/ProductDetail/NXP-Semiconductors/MPXV5050DP?qs=sGAEpiMZZMt7FrWooXVB1zWnaq%252BQl1QQ

**Comment by tubemerc** [comment]
@Kazu-hub 
現状知りたいです．

**Comment by Kazu-hub** [comment]
現状stm32で動作確認できるプログラムは完成してないです…
大室さんから引き継いだarduinoのプログラムをもとにmbedのi2cリファレンスとか見ながら書いてます.

**Comment by tubemerc** [comment]
1/23にMPXV5050DPを動かす、 @Kazu-hub と共に
OR 今日

**Comment by Kazu-hub** [comment]
arduinoで動かしてるやつ
https://github.com/rakibul-eeekuet/Pressure-Sensor-MPXV5050DP/blob/master/pressure_Sensor.ino

**Comment by tubemerc** [comment]
MPXV5050DP
それなりの値がでることを確認．
速度が妥当かどうかは要検証

**Comment by tubemerc** [comment]
動作確認完了．
71e1c1344af5
