### ISSUE TITLE
PX2AN1XX01KPAAAX動作確認 (燃圧)

### ISSUE THREAD

**Issue by tubemerc** [core-rocket/momotarou#9]
購入先：https://www.mouser.jp/ProductDetail/Honeywell/PX2AN1XX750PSAAX?qs=9donYAFoQ1jUT60WHGDXHA%3D%3D

**Comment by tubemerc** [comment]
使い方全く調べてない．
燃焼試験でのマニュアルはある(ただし専用の計測装置を使っている，ロケットには載せられない)．
COREの所有しているコンプレッサーの最大使用圧力0.7MPa．

**Comment by tubemerc** [comment]
STM32F303アナログ入力の動作試験完了．
0V~3.3Vまで検知可能．

圧力計の出力を分圧してから入力して圧力に校正する（動作未確認）．

**Comment by tubemerc** [comment]
DCプラグを購入する
おそらくこれ↓
http://akizukidenshi.com/catalog/g/gC-06513/

**Comment by tubemerc** [comment]
プラグ違いました……

圧力センサ仕様
- Connector：DELPHI 12078088（生産終了？）
- Mating Connector：[DELPHI 12110192](https://www.mouser.jp/ProductDetail/Aptiv-formerly-Delphi/12110192?qs=JdmRl75CwToVcuEd41g61Q%3D%3D)

CORE特性変換ケーブルはDELPHI 12078088を
- RCAプラグ
- DCジャック(7.9x5.5mm)
に変換するので
7.9x5.5mmに対応したDCプラグを探す．

**Comment by tubemerc** [comment]
見つからないので[uxcell DC電源コネクタ アダプタ ジャック 7.9 x 5.5mm オス - 5.5 x 2.5mm メス](https://www.amazon.co.jp/dp/B071YZBG1B/ref=cm_sw_r_tw_dp_U_x_p642DbNS9G6S3)を使って5.5x2.5mmに変換する．

**Comment by tubemerc** [comment]
DCプラグ-USB変換ケーブルなど使って動作確認した．
- null output value : 10% of Vs(5[V]) -> 0.5[V] -> 分圧して0.25[V]
    - STMのanalog入力で0.25[V]を取得できた．

- full scale output value : 90% of Vs(5[V]) -> 4.5[V] -> 分圧して2.25[V]
    - full scale = 5.171[MPa]を作り出すところから始める．
    - コンプレッサーと圧力センサをどうにかして繋ぐ．
        - 円柱をねじ切りしたヤツを介して繋げる．

**Comment by tubemerc** [comment]
@omuro-kairi 
勝部駿を救いたくはないですか？円柱に穴を開けてねじ切りするだけの簡単な仕事です．

**Comment by omuro-kairi** [comment]
救いたくな、喜んで救いたいです。何時までにやれば良いですか？材料の場所も教えて貰えると助かります。

**Comment by tubemerc** [comment]
快く引き受けてくれてありがとう．
次日野来れそうな日いつ？詳細は明日連絡します．

**Comment by omuro-kairi** [comment]
木曜日とかですかね

**Comment by tubemerc** [comment]
ありがとう．
今週の木曜日に日野まで来てください．
詳細は今ここではお伝え出来ません．

**Comment by tubemerc** [comment]
朝野が変換プラグを購入するので加工は無し（？）

**Comment by omuro-kairi** [comment]
了解しました
結局今週も加工出来ませんでした
本当に申し訳ないです

**Comment by tubemerc** [comment]
コンプレッサーを使って試験した．[結果](https://donbrakkoko-skkokoko.slack.com/archives/CLGQNFN4T/p1577441307050700?thread_ts=1577434838.049400&cid=CLGQNFN4T)．

**Comment by tubemerc** [comment]
圧力センサを絶対圧のモノに変更します．
https://www.mouser.jp/ProductDetail/Honeywell/PX2AN1XX01KPAAAX?qs=sGAEpiMZZMvhQj7WZhFIAED7w%2F12p2LVoBtgVBFscYpZrYnWqCQdMw%3D%3D

**Comment by tubemerc** [comment]
#30 に移行
